### ISSUE TITLE
Native macOS menu last duplicate

### ISSUE THREAD

**Issue by timeinpixels** [JamesBoer/ImFrame#5]
On macOS, when adding the MainMenu (natively) I get the last menu entry duplicated:

![duplicate](https://user-images.githubusercontent.com/30871510/211843623-ac03dd87-ff95-411e-abac-691f54ad499c.png)

**Comment by timeinpixels** [comment]
OK, I figured out that it expects Window menu, and I had just the Application menu present.
Is there a quick way to position (my custom, ImGui one) Help menu *after* the Window menu?

**Comment by JamesBoer** [comment]
It's been a while since I worked on the native Mac menu code.  I'll take a peek this weekend and see if anything comes back to me, although honestly, I can't remember actually trying to add a Help menu (nor a Windows menu).  There may be some special requirements for these.

**Comment by timeinpixels** [comment]
I managed to get to a point where I have all the menu items working fine - the only last thing is the ordering. The last menu item is "Window", and Help goes before it (Window menu is created in the resources, Help is created from the code using the OsBeginMenu API). I'd like to have Help menu at the end (as it is in every app on macOS). Tried to play with the logic in the code but there was always some unexpected behaviour with the indexing and I didn't get it right. If you could have a quick look I'd appreciate it!

**Comment by JamesBoer** [comment]
The indexing behavior was indeed tricky.  It took me a while to figure out how to do this.  I decided to add a bool flag to the menu to indicate that you're creating a Help menu.  Another option was to try to automatically detect it via the menu name.  Apple seems to do this, but that felt kind of gross to me, but they're probably more robust, doing it for all support languages or something.  I didn't see a Cocoa API function that indicated that this was a help menu, which would solve the problem nicely, so I went with the flag.  Still another option would be to create a BeginHelpMenu() function.  Feedback on these options is welcome.  

It's actually required to create that menuitem last, because it's doing some trickery with the index to make sure it goes last, past the default Window menu.

I've checked in a patch on the development branch.  The Features example now demonstrates a help menu with an About popup.  Take a look and see if this works for you.  If so, I'll merge it to the main branch.

**Comment by timeinpixels** [comment]
Thanks for looking into it!
I just tried it and there seems to be some issues still.
First of all the assert in OsBeinMenu fails, because Help *is* the last menu, but has a submenu in it (hence another call to OsBeginMenu before OsEndMenuBar is called). But even when I ignore the assert my Window menu is gone and I end up with duplicated Help menu at the end. I got the same when tried to modify it myself earlier.
Maybe I will have a little more time tomorrow to look at it again.
Thanks anyway for taking the time!

**Comment by JamesBoer** [comment]
Ah, yeah... I guess this approach only works with a single additional menu after the Window menu.  I'll see if I can figure out how to make it work with any number of submenus.   May need to re-think the approach a bit.

**Comment by JamesBoer** [comment]
Give the latest development version a try.  I've changed the API to add ImFrame::BeginHelpMenu() instead of a flag to mark the first entry after the Window menu, which I think is a little cleaner.  The Features example now tests dynamically adding menus before and after the Window menu, and it seems reasonably robust.

**Comment by timeinpixels** [comment]
Thank you - the version works well for me! I had to fix one small detail to prevent a crash, but otherwise it works as expected. Appreciate your time!
